import {
  Bot,
  CreditCard,
  FileOutput,
  LayoutDashboard,
  MessagesSquare,
  Settings2,
  Shield,
  Sparkles,
} from "lucide-react";

export const navigationItems = [
  {
    id: "dashboard",
    to: "/dashboard",
    icon: LayoutDashboard,
    labelKey: "nav.dashboard",
    captionKey: "nav.dashboardCaption",
    requiresPlatformAdmin: false,
  },
  {
    id: "knowledge-base",
    to: "/knowledge-base",
    icon: Sparkles,
    labelKey: "nav.knowledgeBase",
    captionKey: "nav.knowledgeBaseCaption",
    requiresPlatformAdmin: false,
  },
  {
    id: "assistant",
    to: "/assistant",
    icon: Bot,
    labelKey: "nav.assistant",
    captionKey: "nav.assistantCaption",
    requiresPlatformAdmin: false,
  },
  {
    id: "conversations",
    to: "/conversations",
    icon: MessagesSquare,
    labelKey: "nav.conversations",
    captionKey: "nav.conversationsCaption",
    requiresPlatformAdmin: false,
  },
  {
    id: "document-engine",
    to: "/document-engine",
    icon: FileOutput,
    labelKey: "nav.documentEngine",
    captionKey: "nav.documentEngineCaption",
    requiresPlatformAdmin: false,
  },
  {
    id: "billing",
    to: "/billing",
    icon: CreditCard,
    labelKey: "nav.billing",
    captionKey: "nav.billingCaption",
    requiresPlatformAdmin: false,
  },
  {
    id: "admin",
    to: "/admin",
    icon: Shield,
    labelKey: "nav.admin",
    captionKey: "nav.adminCaption",
    requiresPlatformAdmin: true,
  },
  {
    id: "settings",
    to: "/settings",
    icon: Settings2,
    labelKey: "nav.settings",
    captionKey: "nav.settingsCaption",
    requiresPlatformAdmin: false,
  },
] as const;
