name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore RootFlow.sln -p:RestoreDisableParallel=true -m:1

      - name: Build
        run: dotnet build RootFlow.sln --no-restore -m:1 --configuration Release

      - name: Test
        run: dotnet test RootFlow.sln --no-build --no-restore -m:1 --configuration Release
